"use client";
import {useEffect,useState,type FormEvent} from "react";
import {useRouter} from "next/navigation";
import {useQuery} from "@tanstack/react-query";
import {usePreferences} from "@/components/ui/providers";
import {ActionForm} from "@/components/ui/action-form";
import {request,type Row,skuLabels} from "@/components/ui/data";
import {Badge,Notice,PageHead} from "@/components/ui/core";
export function Profile({org,profile,onboarding=false}:{org:string;profile:Row;onboarding?:boolean}){
 const {language,theme,setLanguage,setTheme}=usePreferences();const router=useRouter();const [success,setSuccess]=useState("");
 const volunteer=useQuery({queryKey:["workspace",org,"volunteer-profile"],queryFn:()=>request<Row>("/volunteers/me",org),enabled:!!org});
 useEffect(()=>{if(profile.preferred_language==="ta")setLanguage("ta");if(profile.theme==="dark"||profile.theme==="light")setTheme(String(profile.theme))},[profile.preferred_language,profile.theme,setLanguage,setTheme]);
 return <div className="stack"><PageHead eyebrow={onboarding?"WELCOME TO TRUSTGRID":"YOUR ACCOUNT"} title={onboarding?"A little context, a clearer start.":"Profile & availability"} description={onboarding?"Confirm your details and how you would like to participate. Volunteer interest creates an application, not approval.":"Your identity, preferences, and declared volunteer availability."}/>{!org&&<Notice>Your account is signed in, but no organization membership is active. Complete your profile, then ask your administrator for joining access.</Notice>}{success&&<Notice tone="success">{success}</Notice>}<div className="two-col"><section className="panel"><div className="panel-header"><h3>{onboarding?"Set up your account":"Personal details"}</h3></div><div className="panel-body"><div className="avatar-block"><span className="account-initial">{String(profile.display_name||"M").slice(0,1).toUpperCase()}</span><div><strong>{String(profile.display_name||"New member")}</strong><p className="small">{String(profile.email||"Google-connected account")}</p><p className="disclaimer">Manage your sign-in email through Google.</p></div></div><ActionForm org={org} path="/me" method="PATCH" fields={[{key:"display_name",label:"Display name",required:true,value:String(profile.display_name||"")},{key:"preferred_language",label:"Preferred language",value:language,options:[{value:"en",label:"English"},{value:"ta",label:"தமிழ்"}]},{key:"timezone",label:"Timezone",required:true,value:String(profile.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone)},{key:"service_area",label:"Service area",value:String(profile.service_area||"")},{key:"theme",label:"Appearance",value:theme,options:[{value:"light",label:"Light"},{value:"dark",label:"Dark"}]},...(onboarding?[{key:"volunteer",label:"I would like to apply to volunteer",type:"checkbox"}]:[])]} onSaved={r=>{const updated=(r.profile||r) as Row;if(updated.preferred_language==="en"||updated.preferred_language==="ta")setLanguage(updated.preferred_language);if(updated.theme)setTheme(String(updated.theme));setSuccess("Your profile has been saved.");if(onboarding)router.push("/dashboard")}} button={onboarding?"Save and continue":"Save profile"}/></div></section><section className="panel"><div className="panel-header"><h3>Volunteer availability</h3><Badge tone={volunteer.data?.approved?'green':'amber'}>{volunteer.data?.approved===true?"Approved volunteer":"Application required"}</Badge></div><div className="panel-body"><p className="small" style={{marginBottom:20}}>Declare an expiry. Approval, capability, area, and capacity are checked before assignment.</p><VolunteerForm org={org} profile={profile} initial={volunteer.data||undefined} onSaved={()=>{setSuccess("Availability saved. Eligibility is checked before assignment.");void volunteer.refetch()}}/></div></section></div></div>
}
function VolunteerForm({org,profile,initial,onSaved}:{org:string;profile:Row;initial?:Row;onSaved:()=>void}){
 const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [available,setAvailable]=useState(true);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);try{const body={skills:String(form.get('skills')||'').split(',').map(s=>s.trim()).filter(Boolean),areas:String(form.get('areas')||'').split(',').map(s=>s.trim()).filter(Boolean),capacity:Object.fromEntries(Object.keys(skuLabels).map(s=>[s,Number(form.get(s)||0)])),max_tasks:Number(form.get('max_tasks')||1),vehicle:String(form.get('vehicle')),available_until:available?new Date(String(form.get('available_until'))).toISOString():null};await request('/volunteers/me/availability',org,'PATCH',body);onSaved()}catch(e){setError(e instanceof Error?e.message:'Could not save availability.')}finally{setBusy(false)}}
 return <form onSubmit={submit} className="stack-sm"><label className="check-field"><input type="checkbox" checked={available} onChange={e=>setAvailable(e.target.checked)}/>I am currently available to volunteer</label>{available&&<label className="field">Available until (local time)<input name="available_until" type="datetime-local" required/></label>}<label className="field">Service areas<input name="areas" required defaultValue={Array.isArray(initial?.areas)?initial.areas.join(', '):String(profile.service_area||'')}/><small>Separate multiple area names with commas.</small></label><label className="field">Skills / capabilities<input name="skills" required defaultValue={Array.isArray(initial?.skills)?initial.skills.join(', '):'delivery'}/><small>For example: delivery, lifting. Separate with commas.</small></label><div className="field-grid"><label className="field">Travel mode<select name="vehicle" defaultValue={String(initial?.vehicle||'walking')}><option value="walking">Walking</option><option value="bicycle">Bicycle</option><option value="motorcycle">Motorcycle</option><option value="car">Car</option><option value="van">Van</option></select></label><label className="field">Maximum active tasks<input name="max_tasks" type="number" min="1" max="10" defaultValue={Number(initial?.max_tasks||1)} required/></label>{Object.entries(skuLabels).map(([sku,label])=><label className="field" key={sku}>{label} capacity<input name={sku} type="number" min="0" max="1000000" defaultValue={Number((initial?.capacity as Row)?.[sku]||0)} required/></label>)}</div><p className="disclaimer">Capacity is the whole-unit quantity you can safely carry for one task. Use 0 for resources you cannot carry.</p>{error&&<Notice tone="error">{error}</Notice>}<button className="primary" disabled={busy||!org}>{busy?'Saving…':'Update volunteer availability'}</button></form>
}
