import {PGlite} from '@electric-sql/pglite';
import {readFile,readdir} from 'node:fs/promises';
export async function createDatabase(){
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb default '{}');create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;grant usage on schema storage to authenticated;grant select,insert,delete on storage.objects to authenticated;`);
 for(const f of (await readdir('supabase/migrations')).filter(f=>f.endsWith('.sql')).sort())await db.exec(await readFile(`supabase/migrations/${f}`,'utf8'));
 return db;
}
export const ids={admin:'00000000-0000-4000-8000-000000000001',member:'00000000-0000-4000-8000-000000000002',source:'00000000-0000-4000-8000-000000000003',volunteer:'00000000-0000-4000-8000-000000000004',org:'00000000-0000-4000-8000-000000000010',other:'00000000-0000-4000-8000-000000000011'};
export async function seed(db:PGlite){for(const [name,id] of Object.entries(ids).filter(([name])=>!['org','other'].includes(name)))await db.query('insert into auth.users(id,email)values($1,$2)',[id,`${name}@test.invalid`]);await db.query(`insert into organizations(id,name,is_demo)values($1,'Fictional test workspace',true),($2,'Other organization',true)`,[ids.org,ids.other]);for(const [name,id] of Object.entries(ids).filter(([name])=>!['org','other'].includes(name)))await db.query('insert into organization_members(organization_id,user_id,role)values($1,$2,$3)',[ids.org,id,name==='admin'?'admin':'member']);}
export async function asUser<T>(db:PGlite,user:string,sql:string,params:unknown[]=[]){return db.transaction(async tx=>{await tx.exec('set local role authenticated');await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[user]);return(await tx.query<T>(sql,params)).rows;});}
export async function mutate(db:PGlite,user:string,action:string,data:unknown,key=crypto.randomUUID()){const rows=await asUser<{result:Record<string,unknown>}>(db,user,'select tg_mutate($1,$2,$3,$4) as result',[ids.org,action,JSON.stringify(data),key]);return rows[0].result;}
