import {z} from 'zod';
export const skuSchema=z.enum(['WATER_PACK_6X1L','MEAL_KIT','BLANKET','HYGIENE_KIT']);
export const amount=z.number().int().min(1).max(1_000_000);
export const reportSchema=z.object({original_text:z.string().trim().min(3).max(4000),original_language:z.enum(['en','ta','tanglish']).default('en'),kind:z.enum(['need','offer','update']).default('need'),area:z.string().trim().max(200).nullable().default(null),location_precision:z.enum(['unknown','area','pin']).default('area'),latitude:z.number().min(-90).max(90).nullable().optional(),longitude:z.number().min(-180).max(180).nullable().optional(),sku:skuSchema.nullable().default(null),other_category:z.string().max(100).nullable().optional(),quantity:amount.nullable().default(null),quantity_meaning:z.enum(['total','still_needed','unknown']).default('unknown'),urgency:z.enum(['normal','urgent','unknown']).default('unknown'),observed_at:z.string().datetime().nullable().default(null),people_affected:amount.nullable().optional(),extraction_id:z.string().uuid().optional()});
export const offerSchema=z.object({sku:skuSchema,quantity:amount,area:z.string().min(2).max(200),available_until:z.string().datetime()});
export const profileSchema=z.object({display_name:z.string().trim().min(1).max(100),preferred_language:z.enum(['en','ta']).default('en'),timezone:z.string().min(1).max(80).default('Asia/Kolkata'),service_area:z.string().max(200).default(''),theme:z.enum(['light','dark','system']).default('system'),volunteer:z.boolean().optional()});
export const reviewSchema=z.object({action:z.enum(['confirm','clarification_requested','decline','reopen','conflicting']),reason:z.string().min(3).max(1000),version:z.number().int().min(1),priority:z.number().int().min(0).max(5).default(1),target_quantity:amount.optional(),external_received:z.number().int().min(0).default(0),recipient_id:z.string().uuid().optional(),sku:skuSchema.optional(),area:z.string().trim().min(2).max(200).optional(),quantity_meaning:z.enum(['total','still_needed','unknown']).optional()});
export const previewSchema=z.object({sku:skuSchema,policy:z.enum(['urgency','proportional','minimum','manual']),need_ids:z.array(z.string().uuid()).min(1).max(50),lot_ids:z.array(z.string().uuid()).min(1).max(50),targets:z.record(z.string(),z.number().int().min(0)).optional(),manual:z.record(z.string(),z.number().int().min(0)).optional()});

