import Link from "next/link";
import {ArrowUpRight,Check,Info,LoaderCircle,ShieldCheck} from "lucide-react";
export function Logo({dark=false,compact=false}:{dark?:boolean;compact?:boolean}){return <Link className={`logo ${dark?"logo-dark":""}`} href="/" aria-label="TrustGrid home"><svg viewBox="0 0 32 32" width="32" height="32" aria-hidden="true"><path d="M6 7h20M16 7v19M6 7v8m20-8v8" stroke="currentColor" strokeWidth="3" fill="none"/><rect x="2" y="3" width="8" height="8" rx="2" fill="currentColor"/><rect x="12" y="3" width="8" height="8" rx="2" fill="currentColor"/><rect x="22" y="3" width="8" height="8" rx="2" fill="currentColor"/><path d="m10 23 5 5 10-11" stroke="currentColor" strokeWidth="3" fill="none"/></svg>{!compact&&<span>Trust<span className="logo-grid">Grid</span></span>}</Link>}
export function Badge({children,tone="neutral"}:{children:React.ReactNode;tone?:string}){return <span className={`badge ${tone}`}><span className="status-dot"/>{children}</span>}
export function Notice({children,tone="info"}:{children:React.ReactNode;tone?:string}){return <div role={tone==="error"?"alert":"status"} className={`notice ${tone}`}><Info size={18}/><div>{children}</div></div>}
export function Empty({title="No records yet",children}:{title?:string;children?:React.ReactNode}){return <div className="empty"><div className="empty-symbol"><ShieldCheck size={28}/></div><h3>{title}</h3><p>{children||"New records will appear here as your workspace begins coordinating support."}</p></div>}
export function Loading(){return <div className="loading" role="status"><LoaderCircle size={23} className="spin"/> Loading authorized records…</div>}
export function PageHead({eyebrow,title,description,children}:{eyebrow?:string;title:string;description?:string;children?:React.ReactNode}){return <header className="page-head"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{children&&<div className="head-actions">{children}</div>}</header>}
export function Step({n,title,children}:{n:string;title:string;children:React.ReactNode}){return <article className="step"><span className="step-number">{n}</span><h3>{title}</h3><p>{children}</p><Check size={18}/></article>}
export function TextLink({href,children}:{href:string;children:React.ReactNode}){return <Link className="text-link" href={href}>{children}<ArrowUpRight size={16}/></Link>}
