import {PGlite} from '@electric-sql/pglite';
import {readFile,readdir,writeFile} from 'node:fs/promises';
import {connect} from './db.mjs';
let db;
if(process.env.DATABASE_URL)db=await connect();else{
 db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb default '{}');create function auth.uid() returns uuid language sql as $$select null::uuid$$;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid primary key,bucket_id text,name text);`);
 for(const f of (await readdir('supabase/migrations')).filter(f=>f.endsWith('.sql')).sort())await db.exec((await readFile(`supabase/migrations/${f}`,'utf8')).replace(/^\uFEFF/,''));
}
try{
 const {rows}=await db.query("select table_name,column_name,data_type,udt_name,is_nullable,column_default from information_schema.columns where table_schema='public' order by table_name,ordinal_position");
 const type=r=>r.data_type==='ARRAY'?'string[]':['integer','numeric','bigint','smallint','double precision'].includes(r.data_type)?'number':r.data_type==='boolean'?'boolean':r.data_type==='jsonb'?'Json':'string';
 let output='// Generated by npm run db:types from PostgreSQL catalog; do not edit.\nexport type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];\nexport type Database = { public: { Tables: {\n';
 for(const name of new Set(rows.map(r=>r.table_name))){const cols=rows.filter(r=>r.table_name===name);const fields=(insert=false)=>cols.map(r=>`${JSON.stringify(r.column_name)}${insert&&(r.column_default!==null||r.is_nullable==='YES')?'?':''}: ${type(r)}${r.is_nullable==='YES'?' | null':''};`).join('\n');output+=`${JSON.stringify(name)}: { Row: {${fields()}}; Insert: {${fields(true)}}; Update: Partial<{${fields()}}> ; Relationships: [] };\n`;}
 output+='}; Views: Record<string, never>; Functions: { tg_mutate: { Args: {p_org:string;p_action:string;p_data:Json;p_key:string}; Returns:Json }; tg_balances:{Args:{p_org:string};Returns:Json}; tg_session:{Args:Record<string,never>;Returns:Json}; }; Enums: Record<string,never>; CompositeTypes: Record<string,never> } };\n';await writeFile('types/database.ts',output);console.log(`Generated table types for ${new Set(rows.map(r=>r.table_name)).size} tables from ${process.env.DATABASE_URL?'configured database':'isolated PostgreSQL migration runtime'}.`);
}finally{await(db.end?db.end():db.close());}
