-- TrustGrid 1.0: all operational writes use scoped transactional RPCs.
-- UUIDs and SHA-256 use PostgreSQL built-ins.
create schema if not exists private;
revoke all on schema private from public;
create table public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 display_name text not null check(length(display_name) between 1 and 100), email text, avatar_url text,
 preferred_language text not null default 'en' check(preferred_language in ('en','ta')),
 timezone text not null default 'Asia/Kolkata', service_area text not null default '', theme text not null default 'system' check(theme in ('light','dark','system')),
 onboarded boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),last_login_at timestamptz not null default now()
);
create table public.organizations(id uuid primary key default gen_random_uuid(),name text not null,service_areas text[] not null default '{}',settings jsonb not null default '{"hold_minutes":30,"freshness_hours":24}',is_demo boolean not null default false,joining_policy text not null default 'invite' check(joining_policy in ('public','invite')),created_at timestamptz not null default now());
create table public.organization_members(organization_id uuid not null references organizations(id),user_id uuid not null references profiles(id),role text not null default 'member' check(role in ('member','volunteer','coordinator','admin')),status text not null default 'active' check(status in ('active','suspended')),approved_by uuid references profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(organization_id,user_id));
create table public.profile_contacts(id uuid primary key references profiles(id),phone text check(length(phone)<=40),address text check(length(address)<=500),purpose text not null);
create table public.resource_skus(id text primary key,category text not null,label text not null,unit text not null);
insert into resource_skus values ('WATER_PACK_6X1L','water','Water pack (6 × 1 L)','packs'),('MEAL_KIT','meals','Meal kit','kits'),('BLANKET','blankets','Blanket','blankets'),('HYGIENE_KIT','hygiene','Hygiene kit','kits');
create table public.reports(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),author_id uuid not null references profiles(id),original_text text not null check(length(original_text) between 3 and 4000),original_language text not null check(original_language in ('en','ta','tanglish')),kind text not null check(kind in ('need','offer','update')),area text,location_precision text not null default 'unknown' check(location_precision in ('unknown','area','pin')),latitude numeric check(latitude between -90 and 90),longitude numeric check(longitude between -180 and 180),sku text references resource_skus(id),other_category text,quantity integer check(quantity between 1 and 1000000),quantity_meaning text not null check(quantity_meaning in ('total','still_needed','unknown')),urgency text not null check(urgency in ('normal','urgent','unknown')),observed_at timestamptz,people_affected integer check(people_affected>0),review_state text not null default 'awaiting_review' check(review_state in ('awaiting_review','clarification_requested','confirmed','declined','conflicting')),review_reason text,cancellation_requested boolean not null default false,version integer not null default 1,received_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id),foreign key(organization_id,author_id) references organization_members(organization_id,user_id));
create table public.report_extractions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),author_id uuid not null references profiles(id),report_id uuid,original_text text not null check(length(original_text)<=4000),draft jsonb not null,corrections jsonb,model text not null,schema_version text not null,created_at timestamptz not null default now(),foreign key(organization_id,report_id) references reports(organization_id,id));
create table public.report_attachments(id uuid primary key default gen_random_uuid(),organization_id uuid not null,report_id uuid not null,uploader_id uuid not null references profiles(id),path text not null unique,mime text not null check(mime in ('image/jpeg','image/png','image/webp')),size integer not null check(size between 1 and 5242880),created_at timestamptz not null default now(),foreign key(organization_id,report_id) references reports(organization_id,id));
create table public.needs(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),sku text not null references resource_skus(id),area text not null,recipient_id uuid not null,target_quantity integer not null check(target_quantity between 1 and 1000000),external_received integer not null default 0 check(external_received>=0),priority integer not null check(priority between 0 and 5),status text not null default 'confirmed' check(status in ('confirmed','closed')),version integer not null default 1,confirmed_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id),foreign key(organization_id,recipient_id) references organization_members(organization_id,user_id),check(external_received<=target_quantity));
create table public.need_report_links(organization_id uuid not null,need_id uuid not null,report_id uuid not null,actor_id uuid not null references profiles(id),created_at timestamptz not null default now(),primary key(need_id,report_id),foreign key(organization_id,need_id) references needs(organization_id,id),foreign key(organization_id,report_id) references reports(organization_id,id));
create table public.report_relationships(id uuid primary key default gen_random_uuid(),organization_id uuid not null,source_id uuid not null,target_id uuid not null,kind text not null check(kind in ('duplicate','update','conflicting')),reason text not null,actor_id uuid not null references profiles(id),reversed_at timestamptz,created_at timestamptz not null default now(),foreign key(organization_id,source_id) references reports(organization_id,id),foreign key(organization_id,target_id) references reports(organization_id,id),check(source_id<>target_id));
create table public.review_decisions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),report_id uuid,need_id uuid,actor_id uuid not null references profiles(id),action text not null,reason text not null,previous_state text,new_state text,created_at timestamptz not null default now(),foreign key(organization_id,report_id) references reports(organization_id,id),foreign key(organization_id,need_id) references needs(organization_id,id));
create table public.resource_offers(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),donor_id uuid not null,sku text not null references resource_skus(id),quantity integer not null check(quantity between 1 and 1000000),area text not null,available_until timestamptz not null,status text not null default 'offered' check(status in ('offered','confirmed','withdrawn')),version integer not null default 1,created_at timestamptz not null default now(),unique(organization_id,id),foreign key(organization_id,donor_id) references organization_members(organization_id,user_id));
create table public.inventory_lots(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),offer_id uuid,source_id uuid not null,sku text not null references resource_skus(id),area text not null,on_hand integer not null check(on_hand>=0),held boolean not null default false,confirmed_at timestamptz not null default now(),fresh_until timestamptz not null,expires_at timestamptz not null,version integer not null default 1,unique(organization_id,id),unique(offer_id),foreign key(organization_id,offer_id) references resource_offers(organization_id,id),foreign key(organization_id,source_id) references organization_members(organization_id,user_id));
create table public.allocation_scenarios(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),author_id uuid not null references profiles(id),sku text not null references resource_skus(id),policy text not null,input jsonb not null,result jsonb not null,algorithm_version text not null,created_at timestamptz not null default now(),unique(organization_id,id));
create table public.allocations(id uuid primary key default gen_random_uuid(),organization_id uuid not null,scenario_id uuid not null,need_id uuid not null,sku text not null references resource_skus(id),quantity integer not null check(quantity>0),created_at timestamptz not null default now(),unique(organization_id,id),foreign key(organization_id,scenario_id) references allocation_scenarios(organization_id,id),foreign key(organization_id,need_id) references needs(organization_id,id),unique(scenario_id,need_id));
create table public.reservations(id uuid primary key default gen_random_uuid(),organization_id uuid not null,allocation_id uuid not null,lot_id uuid not null,quantity integer not null check(quantity>0),remaining integer not null check(remaining>=0),expires_at timestamptz not null,state text not null default 'active' check(state in ('active','expired','released','collected')),version integer not null default 1,created_at timestamptz not null default now(),unique(organization_id,id),foreign key(organization_id,allocation_id) references allocations(organization_id,id),foreign key(organization_id,lot_id) references inventory_lots(organization_id,id),check(remaining<=quantity));
create table public.volunteer_profiles(organization_id uuid not null,user_id uuid not null,approved boolean not null default false,skills text[] not null default '{}',areas text[] not null default '{}',capacity jsonb not null default '{}',max_tasks integer not null default 1 check(max_tasks between 1 and 10),available_until timestamptz,vehicle text not null default 'none',service_radius_km numeric not null default 5 check(service_radius_km between 0 and 200),latitude numeric,longitude numeric,location_at timestamptz,updated_at timestamptz not null default now(),primary key(organization_id,user_id),foreign key(organization_id,user_id) references organization_members(organization_id,user_id));
create table public.delivery_tasks(id uuid primary key default gen_random_uuid(),organization_id uuid not null,reservation_id uuid not null,volunteer_id uuid,proposed_volunteer_id uuid,source_id uuid not null,recipient_id uuid not null,sku text not null references resource_skus(id),area text not null,quantity integer not null check(quantity>0),picked_up integer not null default 0,received integer not null default 0,returned integer not null default 0,lost integer not null default 0,required_skill text, state text not null default 'awaiting_assignment' check(state in ('awaiting_assignment','accepted','pickup_confirmed','en_route','dropoff_recorded','receipt_confirmed','closed','cancelled_before_pickup','exception')),version integer not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id),foreign key(organization_id,reservation_id) references reservations(organization_id,id),foreign key(organization_id,proposed_volunteer_id) references organization_members(organization_id,user_id),foreign key(organization_id,volunteer_id) references organization_members(organization_id,user_id),foreign key(organization_id,source_id) references organization_members(organization_id,user_id),foreign key(organization_id,recipient_id) references organization_members(organization_id,user_id),check(picked_up between 0 and quantity),check(received>=0 and returned>=0 and lost>=0 and received+returned+lost<=picked_up));
create table public.task_events(id uuid primary key default gen_random_uuid(),organization_id uuid not null,task_id uuid not null,actor_id uuid not null references profiles(id),action text not null,reason text,quantity integer,created_at timestamptz not null default now(),foreign key(organization_id,task_id) references delivery_tasks(organization_id,id));
create table public.handoff_challenges(id uuid primary key default gen_random_uuid(),organization_id uuid not null,task_id uuid not null,step text not null check(step in ('pickup','delivery')),issuer_id uuid not null references profiles(id),actor_id uuid not null references profiles(id),digest text not null,quantity integer not null check(quantity>0),expires_at timestamptz not null,attempts integer not null default 0,consumed_at timestamptz,created_at timestamptz not null default now(),foreign key(organization_id,task_id) references delivery_tasks(organization_id,id));
create table public.inventory_movements(id uuid primary key default gen_random_uuid(),organization_id uuid not null,lot_id uuid not null,need_id uuid,task_id uuid,actor_id uuid references profiles(id),kind text not null check(kind in ('confirm','adjust','reserve','release','pickup','receipt','return','loss')),quantity integer not null check(quantity<>0),reason text not null,idempotency_key text,created_at timestamptz not null default now(),foreign key(organization_id,lot_id) references inventory_lots(organization_id,id),foreign key(organization_id,need_id) references needs(organization_id,id),foreign key(organization_id,task_id) references delivery_tasks(organization_id,id));
create table public.notifications(id uuid primary key default gen_random_uuid(),organization_id uuid not null,user_id uuid not null,message text not null,entity_type text,entity_id uuid,read_at timestamptz,created_at timestamptz not null default now(),foreign key(organization_id,user_id) references organization_members(organization_id,user_id));
create table public.admin_notes(id uuid primary key default gen_random_uuid(),organization_id uuid not null,subject_id uuid not null,author_id uuid not null references profiles(id),body text not null check(length(body) between 1 and 2000),created_at timestamptz not null default now(),foreign key(organization_id,subject_id) references organization_members(organization_id,user_id));
create table public.audit_events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),actor_id uuid references profiles(id),action text not null,entity_id uuid,reason text,changes jsonb not null default '{}',correlation_id text,created_at timestamptz not null default now());
create table public.idempotency_records(organization_id uuid not null references organizations(id),actor_id uuid not null references profiles(id),key text not null check(length(key) between 8 and 128),payload_hash text not null,outcome jsonb not null,created_at timestamptz not null default now(),primary key(organization_id,actor_id,key));
create table public.rate_limit_buckets(user_id uuid not null references profiles(id),action text not null,window_start timestamptz not null,count integer not null,primary key(user_id,action,window_start));
create index report_queue on reports(organization_id,review_state,received_at desc,id);
create index report_owner on reports(author_id,received_at desc);
create index need_queue on needs(organization_id,status,confirmed_at,id);
create index lot_lookup on inventory_lots(organization_id,sku,area);
create index active_reservations on reservations(organization_id,lot_id,expires_at) where state='active';
create index tasks_assignee on delivery_tasks(organization_id,volunteer_id,state);
create index notifications_unread on notifications(user_id,created_at desc) where read_at is null;
create index audit_lookup on audit_events(organization_id,created_at desc,id);
create index offer_owner on resource_offers(organization_id,donor_id,created_at desc);
create index task_event_lookup on task_events(task_id,created_at);
create index movement_lookup on inventory_movements(organization_id,lot_id,created_at);
create index allocation_need on allocations(organization_id,need_id);
create index challenge_lookup on handoff_challenges(task_id,step,created_at desc);
create or replace function private.role(org uuid) returns text language sql stable security definer set search_path='' as $$ select role from public.organization_members where organization_id=org and user_id=auth.uid() and status='active' $$;
create or replace function private.staff(org uuid) returns boolean language sql stable security definer set search_path='' as $$ select coalesce(private.role(org) in ('coordinator','admin'),false) $$;
create or replace function private.can_report(org uuid,rid uuid) returns boolean language sql stable security definer set search_path='' as $$select private.role(org) is not null and exists(select 1 from public.reports where id=rid and organization_id=org and (author_id=auth.uid() or private.staff(org)))$$;
create or replace function private.can_task(org uuid,tid uuid) returns boolean language sql stable security definer set search_path='' as $$select private.role(org) is not null and exists(select 1 from public.delivery_tasks where id=tid and organization_id=org and (auth.uid() in (source_id,recipient_id,volunteer_id) or private.staff(org)))$$;
-- Helpers are callable in policies only; no unauthenticated data.
grant usage on schema private to authenticated;
grant execute on function private.role(uuid),private.staff(uuid),private.can_report(uuid,uuid),private.can_task(uuid,uuid) to authenticated;
do $$ declare t record; begin for t in select tablename from pg_tables where schemaname='public' loop execute format('alter table public.%I enable row level security',t.tablename); execute format('revoke all on public.%I from anon, authenticated',t.tablename); execute format('grant select on public.%I to authenticated',t.tablename); end loop; end $$;
create policy own_profile on profiles for select to authenticated using(id=auth.uid() or exists(select 1 from organization_members m where m.user_id=profiles.id and private.role(m.organization_id)='admin'));
create policy own_contact on profile_contacts for select to authenticated using(id=auth.uid());
create policy member_org on organizations for select to authenticated using(private.role(id) is not null);
create policy scoped_members on organization_members for select to authenticated using(private.role(organization_id) is not null and (user_id=auth.uid() or private.staff(organization_id)));
create policy sku_read on resource_skus for select to authenticated using(true);
create policy report_read on reports for select to authenticated using(private.role(organization_id) is not null and (author_id=auth.uid() or private.staff(organization_id)));
create policy extraction_read on report_extractions for select to authenticated using(private.role(organization_id) is not null and (author_id=auth.uid() or private.staff(organization_id)));
create policy attachment_read on report_attachments for select to authenticated using(private.can_report(organization_id,report_id));
create policy need_read on needs for select to authenticated using(private.role(organization_id) is not null and (recipient_id=auth.uid() or private.staff(organization_id)));
create policy offer_read on resource_offers for select to authenticated using(private.role(organization_id) is not null and (donor_id=auth.uid() or private.staff(organization_id)));
create policy volunteer_read on volunteer_profiles for select to authenticated using(private.role(organization_id) is not null and (user_id=auth.uid() or private.staff(organization_id)));
create policy task_read on delivery_tasks for select to authenticated using(private.can_task(organization_id,id));
create policy event_read on task_events for select to authenticated using(private.can_task(organization_id,task_id));
create policy own_notification on notifications for select to authenticated using(user_id=auth.uid() and private.role(organization_id) is not null);
create policy notes_admin on admin_notes for select to authenticated using(private.role(organization_id)='admin');
create policy audit_admin on audit_events for select to authenticated using(private.role(organization_id)='admin');
create policy decision_read on review_decisions for select to authenticated using(private.can_report(organization_id,report_id));
create policy link_read on need_report_links for select to authenticated using(private.can_report(organization_id,report_id));
do $$ declare t text; begin foreach t in array array['report_relationships','inventory_lots','inventory_movements','allocation_scenarios','allocations','reservations'] loop execute format('create policy staff_read on public.%I for select to authenticated using(private.staff(organization_id))',t);end loop;end$$;
-- No client SELECT policy on challenges, idempotency and rate buckets.
create or replace function private.new_user() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(id,display_name,email,avatar_url) values(new.id,left(coalesce(nullif(new.raw_user_meta_data->>'full_name',''),'Community member'),100),new.email,new.raw_user_meta_data->>'avatar_url') on conflict(id) do nothing; return new;end$$;
create trigger trustgrid_profile after insert on auth.users for each row execute function private.new_user();
create or replace function public.tg_session() returns jsonb language plpgsql security definer set search_path='' as $$ begin if auth.uid() is null then raise exception 'AUTH_REQUIRED';end if; insert into public.profiles(id,display_name,email,avatar_url) select id,left(coalesce(nullif(raw_user_meta_data->>'full_name',''),'Community member'),100),email,raw_user_meta_data->>'avatar_url' from auth.users where id=auth.uid() on conflict(id) do update set last_login_at=now(),email=excluded.email,avatar_url=excluded.avatar_url; insert into public.organization_members(organization_id,user_id) select id,auth.uid() from public.organizations where joining_policy='public' on conflict do nothing; return jsonb_build_object('ok',true); end $$;
create or replace function public.tg_rate_limit(p_action text) returns boolean language plpgsql security definer set search_path='' as $$ declare c integer;w timestamptz:=date_trunc('hour',now());begin if auth.uid() is null then return false;end if;insert into public.rate_limit_buckets values(auth.uid(),left(p_action,50),w,1) on conflict(user_id,action,window_start) do update set count=rate_limit_buckets.count+1 returning count into c;delete from public.rate_limit_buckets where window_start<now()-interval '2 days';return c<=case when p_action='extract' then 20 else 300 end;end$$;
create or replace function private.expire_org(org uuid) returns integer language plpgsql security definer set search_path='' as $$ declare r record; n integer:=0;begin for r in select * from public.reservations where organization_id=org and state='active' and expires_at<=now() for update loop if r.remaining>0 then insert into public.inventory_movements(organization_id,lot_id,kind,quantity,reason) values(org,r.lot_id,'release',r.remaining,'Reservation expired');end if;update public.reservations set state='expired',remaining=0,version=version+1 where id=r.id;update public.delivery_tasks set state='cancelled_before_pickup',version=version+1,updated_at=now() where reservation_id=r.id and picked_up=0 and state in ('awaiting_assignment','accepted');update public.inventory_lots set version=version+1 where id=r.lot_id;n:=n+1;end loop;return n;end$$;
create or replace function private.need_uncommitted(nid uuid) returns integer language sql stable security definer set search_path='' as $$select greatest(0,n.target_quantity-n.external_received-coalesce((select sum(t.received+t.picked_up-t.received-t.returned-t.lost) from public.delivery_tasks t join public.reservations r on r.id=t.reservation_id join public.allocations a on a.id=r.allocation_id where a.need_id=n.id),0)-coalesce((select sum(r.remaining) from public.reservations r join public.allocations a on a.id=r.allocation_id where a.need_id=n.id and r.state='active' and r.expires_at>now()),0))::integer from public.needs n where n.id=nid$$;
create or replace function private.lot_available(lid uuid) returns integer language sql stable security definer set search_path='' as $$select case when held or fresh_until<=now() or expires_at<=now() then 0 else on_hand-coalesce((select sum(remaining) from public.reservations where lot_id=l.id and state='active' and expires_at>now()),0) end::integer from public.inventory_lots l where id=lid$$;
create or replace function public.tg_balances(p_org uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$begin if not private.staff(p_org) then raise exception 'FORBIDDEN';end if;return jsonb_build_object('needs',(select coalesce(jsonb_agg(to_jsonb(n)||jsonb_build_object('uncommitted',private.need_uncommitted(n.id))), '[]') from public.needs n where organization_id=p_org and status='confirmed'),'lots',(select coalesce(jsonb_agg(to_jsonb(l)||jsonb_build_object('available',private.lot_available(l.id))), '[]') from public.inventory_lots l where organization_id=p_org));end$$;
revoke all on all functions in schema private from public;
revoke all on function public.tg_session(),public.tg_rate_limit(text),public.tg_balances(uuid) from public,anon;
grant execute on function public.tg_session(),public.tg_rate_limit(text),public.tg_balances(uuid) to authenticated;

